LTO_ENABLE = yes

CONSOLE_ENABLE = no

SLEEP_LED_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no

AVR_USE_MINIMAL_PRINTF = yes

NKRO_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
